/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scrollbar: typeof import('./src/components/Scrollbar/Scrollbar.vue')['default']
    TCheckTagGroup: typeof import('tdesign-vue-next')['CheckTagGroup']
    TCol: typeof import('tdesign-vue-next')['Col']
    TLoading: typeof import('tdesign-vue-next')['Loading']
    TRow: typeof import('tdesign-vue-next')['Row']
    TTag: typeof import('tdesign-vue-next')['Tag']
  }
}
